Adding WNUT_2020_NER dataset support
flairNLP/flair pull request #1942
Opened 2020-11-05 17:21 UTC by aynetdia

This implementation appropriately prepares and loads the aforementioned dataset. 

I could also add commit the testing function for the piping testing, if needed.

2020-11-06 05:17 UTC, alanakbik requested changes

2020-11-06 05:17 UTC, alanakbik commented on flair/datasets/sequence_labeling.py
> +                unpack_file(zip_path, data_folder, "zip", False) # unzipped folder name: WNUT_2020_NER-master
I believe the method `unpack_file` is missing. Perhaps you forgot to check it in?

2020-11-06 05:17 UTC, alanakbik commented on flair/datasets/sequence_labeling.py
> +                unpack_file(zip_path, data_folder, "zip", False) # unzipped folder name: WNUT_2020_NER-master
Ah no, only the import statement is missing. Can you add `from flair.file_utils import unpack_file`?

2020-11-06 05:19 UTC, alanakbik commented
@aynetdia thanks for adding this! There is an import statement missing - can you add it? 

Also, I notice the statistics of the corpus are slightly off. If I print the `WNUT_2020_NER` object, I get: 

Corpus: **8075** train + 2740 dev + 2691 test sentences

But the task website at https://github.com/jeniyat/WNUT_2020_NER lists the following statistics: 

-    train_data: 370 protocols with **8444** sentences
-    dev_data: 122 protocols with 2839 sentences
-    test_data: 123 protocols with 2813 sentences

Could you double-check?

2020-11-06 09:56 UTC, aynetdia commented
I was able to fix the corpus length problem, however only for the train_data and test_data. Now they contain 8444 and 2813 sentences respectively. However the dev_data contains 2862 sentences instead of 2839 as specified in the GitHub repo. 

Not sure what the reason for the discrepancy - I went over the whole dev sample manually and couldn't notice any obvious irregularities.

2020-11-09 10:20 UTC, alanakbik approved these changes

2020-11-09 10:23 UTC, alanakbik commented
@aynetdia thanks for updating the PR! 

Just one more item: There is a folder for the [2020 version of the test data](https://github.com/jeniyat/WNUT_2020_NER/tree/master/data/test_data_2020) (called `test_data_2020`), which contains a lot more sentences. Their [paper](http://noisy-text.github.io/2020/pdf/2020.d200-1.33.pdf) (see Table 1) distinguishes between Text-18 and Test-20 datasets. Test-20 is what was used to evaluate and has 3562 sentences. Can you change it so that `test_data_2020` is used instead of `test_data`?

2020-11-09 19:57 UTC, alanakbik commented
@aynetdia thanks for adding this!

2020-11-09 19:57 UTC, merged