flair with the webpages dataset
flairNLP/flair pull request #2232
Opened 2021-04-19 11:53 UTC by TatianaMoteuN

2021-04-19 14:18 UTC, alanakbik requested changes

2021-04-19 14:18 UTC, alanakbik commented on flair/datasets/sequence_labeling.py
> +
Can you add a routine here that downloads and unpacks the tgz file? The resulting files should then be concatenated into a single file for reading.

2021-04-21 05:29 UTC, alanakbik commented
@TatianaMoteuN thanks for adding this - everything seems to work now!

Can you remove the file `test.2.py` from the PR? Then we can merge.

2021-04-21 07:55 UTC, TatianaMoteuN commented
> @TatianaMoteuN thanks for adding this - everything seems to work now!
> 
> Can you remove the file `test.2.py` from the PR? Then we can merge.

 @alanakbik the PR does not contain that file. not sure but where do you see it?

2021-04-27 06:59 UTC, alanakbik approved these changes

2021-04-27 06:59 UTC, alanakbik commented
@TatianaMoteuN thanks for adding this!

2021-04-27 06:59 UTC, merged