small lm training improvements
flairNLP/flair pull request #2590
Opened 2022-01-06 21:12 UTC by helpmefindaname

fix lm training (fix https://github.com/flairNLP/flair/issues/2577 )
nice output in lm training
allow usage of lstm and gru in flair lm
remove unnecessary imports in flair/__init__.py

2022-01-27 10:09 UTC, alanakbik requested changes
Thanks for improving this and sorry for the late review! It mostly looks good, but the GRU is currently not working, i.e. 

```python
language_model = LanguageModel(
    dictionary,
    is_forward_lm=True,
    hidden_size=128,
    nlayers=1,
    recurrent_type="GRU",
)

# train your language model
trainer = LanguageModelTrainer(language_model, corpus)

# train your language model

trainer.train(
    "resources/LMs/test",
...
```

due to the hidden state being created for LSTM.

2022-01-27 10:09 UTC, alanakbik commented on flair/models/language_model.py
> +        return w1, w2
in a GRU, only a single state is needed

2022-01-27 10:09 UTC, alanakbik commented on flair/trainers/trainer.py
>                      # or deleted
I guess the comments on storing embeddings should move too ;)

2022-01-29 13:41 UTC, helpmefindaname commented
my bad, I removed the states part again, as when I removed the SRU again,
now it should work

2022-02-02 09:44 UTC, alanakbik approved these changes

2022-02-02 09:44 UTC, alanakbik commented
@helpmefindaname looks great, thanks for improving this!

2022-02-02 09:44 UTC, merged