fix: patch the missing `document_delmiter` for `lm.__get_state__()`
flairNLP/flair pull request #2658
Opened 2022-03-07 14:05 UTC by tianjianjiang

There are already similar special treatments like https://github.com/flairNLP/flair/blob/master/flair/embeddings/token.py#L724 and https://github.com/flairNLP/flair/blob/master/flair/models/language_model.py#L190, but we will still need this for pre-trained `SequenceTagger` or alike to be pickle-able (for Dill and/or multiprocessing).

2022-03-13 15:41 UTC, tadejmagajna requested changes
Thank you for your time and for figuring out the solution for this not-so-uncommon problem!

I did some investigation and found out that the root of this problem. The cause of this issue
is that some older serialized `LanguageModel`s don't have the `document_delimiter` property because it didn't exist at the time those models were trained.

For clarity I therefore suggest adding a small comment that explains the reason this workaround is needed.

Also, I suggest the use of `getattr` which is a bit more straight-forward and cleaner (no if statement needed) than the use of `self.__dict__`


Happy to approve otherwise!

2022-03-13 15:41 UTC, tadejmagajna commented on flair/models/language_model.py
> +            self.document_delimiter = "\n"
```suggestion
        # "document_delimiter" property may be missing in some older pre-trained models
        self.document_delimiter = getattr(self, "document_delimiter", "\n")
```

2022-03-15 10:30 UTC, alanakbik commented
@tianjianjiang thanks for fixing this!

2022-03-15 10:30 UTC, merged

2022-04-02 07:42 UTC, tianjianjiang commented
I'm sorry for letting this falling through the cracks.
Really appreciate the review, @tadejmagajna, and I'm gonna provide some context just in case.
And of course, @alanakbik, thank you for the approval.

> For clarity I therefore suggest adding a small comment that explains the reason this workaround is needed.

BLUF: I'm all for it and pardon me for being too late to add that comment.
Context: Besides me been being lazy and careless, I had a vague hesitance because no comments with https://github.com/flairNLP/flair/blob/master/flair/embeddings/token.py#L724 and https://github.com/flairNLP/flair/blob/master/flair/models/language_model.py#L190, such that I was just hoping it could be an excuse to leave no comments about this (since I didn't carefully check whether flair has a convention of inline comment).


> Also, I suggest the use of `getattr` which is a bit more straight-forward and cleaner (no if statement needed) than the use of `self.__dict__`

BLUF: It crossed my mind but I would also like to change other near-identical lines. Yet I didn't want to change too many lines.
Context: I do agree that `getattr` is good for brevity, and I also think it's nice to respect the descriptor protocol. However, I am still unsure the intent behind other pre-existed, near-identical lines, e.g., what if those lines want to fail when a class doesn't have `__dict__`.


Again, thank you guys for all the support. Cheers!