GH-3474: add random seed parameter to dataset splitting and downsampl…
flairNLP/flair pull request #3475
Opened 2024-06-21 23:44 UTC by MattGPT-ai

https://github.com/flairNLP/flair/issues/3474

Adds random seed parameters to dataset splitting and downsampling functions

2024-06-28 14:01 UTC, helpmefindaname requested changes
Hi @MattGPT-ai
thank you for your contribution.
The changes look good to me, I just requests a small change. Besides that, I think this is ready to merge

2024-06-28 14:11 UTC, helpmefindaname commented on flair/data.py
> +) -> tuple[Subset, Subset]:
Please use `Tuple` (from typing import Tuple) to allow compability with older python versions

2024-06-28 17:39 UTC, MattGPT-ai commented
Thanks for your review! Pushed the changes you requested

2024-06-29 00:19 UTC, helpmefindaname approved these changes

2024-06-29 03:41 UTC, MattGPT-ai commented
Thanks for the approval! How can we trigger the checks to run so that it can be merged?

2024-07-01 13:42 UTC, alanakbik commented on flair/data.py
>      indices = list(range(len(dataset)))
```suggestion
    indices = list(range(_len_dataset(dataset)))
```

2024-07-01 14:16 UTC, alanakbik requested changes
Thanks for the PR! Looks good, but there is a small mypy error (I added a suggestion to fix).

2024-07-01 18:20 UTC, MattGPT-ai commented
Applied the change. I had a question, I saw that step is necessary because Dataset doesn't have `__len__` implemented. Is there a way to implement `__len__`, even if it just calls `_len_dataset`? Does constructing the `DatasetLoader` class take any non-negligible time? I actually see the same warning for `return len(loader)` in my PyCharm that it "Expected type Sized, got DataLoader instead", and a similar warning for `_iter_dataset`

2024-07-02 03:04 UTC, alanakbik commented
Thanks! I agree that it would be better to implement `__len__` rather than having to call `_len_dataset`. 

The problem is that `Dataset` is a PyTorch class that does not have `__len__` or `__iter__` implemented, so we can't add them here. Alternatively, we might change the code that instead of `Dataset`, everything is based on either PyTorch's `IterDataset` or our own `FlairDataset`.

2024-07-02 07:44 UTC, alanakbik approved these changes

2024-07-02 07:45 UTC, alanakbik commented
@MattGPT-ai thanks a lot for adding this!

2024-07-02 07:45 UTC, merged