Adds DataTriples which act just like DataPairs
flairNLP/flair pull request #3481
Opened 2024-07-01 08:05 UTC by janpf

This adds a new DataPoint type consisting of three sentences instead of two. This could/should likely be parameterizable, but this is the easiest way to add this.

2024-07-01 10:00 UTC, alanakbik commented on flair/data.py
> +    def clear_embeddings(self, embedding_names: List[str] = None):
```suggestion
    def clear_embeddings(self, embedding_names: Optional[List[str]] = None):
```

2024-07-01 10:01 UTC, alanakbik commented on flair/data.py
> +    def clear_embeddings(self, embedding_names: List[str] = None):
Should be consistent with signature of supertype

2024-07-01 10:02 UTC, alanakbik commented on flair/datasets/text_text.py
> +        label_type: str = None,
```suggestion
        label_type: Optional[str] = None,
```

2024-07-01 10:02 UTC, alanakbik commented on flair/datasets/text_text.py
> +        label_type: str = None,
Implicit optionals are no longer allowed

2024-07-01 10:04 UTC, alanakbik commented on flair/datasets/text_text.py
> +        label_type: str = None,
```suggestion
        label_type: Optional[str] = None,
```

2024-07-01 10:05 UTC, alanakbik requested changes
Thanks for the PR! Just some minor mypy problems, concerning implicit optionals. I've added some suggestions as comments to fix the issues.

2024-07-02 07:47 UTC, alanakbik approved these changes

2024-07-02 07:48 UTC, alanakbik commented
@janpf thanks a lot for adding this! Will you also add some prepared corpora for the SuperGLEBler datasets in future PRs?

2024-07-02 07:48 UTC, merged

2024-07-02 07:58 UTC, janpf commented
> @janpf thanks a lot for adding this! Will you also add some prepared corpora for the SuperGLEBler datasets in future PRs?

Thanks for the quick merge, @alanakbik :)
We are thinking about it. Currently, we provide the datasets via the repo, which was the fastest way to deliver the files. I think we'll make sure version 0.13 works nicely, and then we'll see :)

Is there an ETA for when the two PRs might land on pypi? :)

2024-07-02 08:01 UTC, alanakbik commented
I'm hoping to find enough time to prepare a new release once the semester ends (in two weeks).