GH-3509: fix support metric
flairNLP/flair pull request #3510
Opened 2024-07-24 09:36 UTC by MattGPT-ai

Addresses https://github.com/flairNLP/flair/issues/3509

Also adds more type hinting and fixes mutable default arguments.

2024-07-25 17:15 UTC, MattGPT-ai commented
I'm not sure what the error occurring is, it doesn't seem to be related to my changes but maybe you are familiar with it

2024-08-01 16:49 UTC, MattGPT-ai commented
Looks like the test passed without me changing anything, so this should be ready for review

2024-08-09 07:51 UTC, alanakbik commented on flair/nn/model.py
> +        """This appears to have not been fully implemented and simply returns scores."""
In most models, scores are not masked, so the default implementation is to just return the scores. The `SpanClassifier` overwrites this method to account for "candidate lists". Anything not on these lists, will be masked.

2024-08-09 08:06 UTC, alanakbik requested changes
Looks good, thanks for adding this! Just needs a tiny modification in one of the comment lines, as otherwise it would be misleading.

2024-08-09 08:06 UTC, alanakbik commented on flair/nn/model.py
> +        """This appears to have not been fully implemented and simply returns scores."""
```suggestion
        """Classes that inherit from DefaultClassifier may optionally mask scores."""
```

2024-08-11 13:28 UTC, merged

2024-08-11 13:28 UTC, alanakbik commented
@MattGPT-ai thanks for fixing this!